jdk:
  - oraclejdk8
language: android

before_install:
  - echo yes | android update sdk --all --filter build-tools-22.0.1 --no-ui --force > /dev/null

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra
    - extra-android-m2repository
  licenses:
    - android-sdk-license-[0-9a-f]{8}
    - '.*intel.+'

script:
   - ./gradlew build :sample:connectedCheck