language: android

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-m2repository
  licenses:
    - android-sdk-license-[0-9a-f]{8}
    - '.*intel.+'

install:
  # Prevent `gradle assemble` from being invoked by overriding with no-op
  - true

script:
   - ./gradlew build