language: android

android:
  components:
    - build-tools-22.0.0
    - android-22
    - extra-android-m2repository
  licenses:
    - android-sdk-license-[0-9a-f]{8}
    - '.*intel.+'

script:
   - ./gradlew build